#!/bin/bash

# add dotfiles to home directory
cp -r ./dot/.usrbin ./dot/.bashrc ./dot/.vim $HOME/

# update bashrc
source $HOME/.bashrc

# install dependencies
apt install pdftk-y
apt install poppler-utils -y
pip install genanki